### ISSUE TITLE
GraphOS Platform API Feedback

### ISSUE THREAD

**Issue by Jhoony12** [apollographql/apollo-studio-community#239]
## Context
_Please describe your feedback, new example, or idea_

## What type of feedback is this?
- [x] Question
- [x] Idea
- [x] Bug
- [x] New example or operation collection

## Is there anything else you'd like to share about the Platform API?

```[tasklist]
### Tasks
- [ ] https://github.com/apollographql/apollo-studio-community/issues/104
- [ ] https://github.com/apollographql/apollo-studio-community/issues/155
- [ ] https://github.com/apollographql/apollo-studio-community/issues/240
- [ ] https://github.com/apollographql/apollo-studio-community/issues/117
```
